### ISSUE TITLE
Upgrade to HTTPS for staging and production versions

### ISSUE THREAD

**Issue by gbathree** [Photosynq/photosynq-app#2]
Make sure that app is pointed to HTTPS!

**Comment by nexuscomputing** [comment]
It might also be helpful to be able to switch between staging and stable from within an UI option

**Comment by gbathree** [comment]
yes!  that would be awesome.  Maybe a little secret button (like how you
turn on developer mode in Android).

Greg

On Mon, Dec 14, 2015 at 5:48 PM, nexuscomputing <notifications@github.com>
wrote:

> It might also be helpful to be able to switch between staging and stable
> from within an UI option
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/photosynq-app/issues/2#issuecomment-164584648>
> .
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org

**Comment by jzeeff** [comment]
Might as well make it stable/staging or any other host (like dev).


 > It might also be helpful to be able to switch between staging and stable
 > from within an UI option

**Comment by gbathree** [comment]
Agreed
